### ISSUE TITLE
Make Ignoring the main package optional

### ISSUE THREAD

**Issue by jvm986** [PanagiotisPtr/cov-diff#10]
i.e. --> https://github.com/PanagiotisPtr/cov-diff/blob/55d468b23fab866d88cb894f51d443b961ca92ff/files/files.go#L78

I can create a PR for this

**Comment by PanagiotisPtr** [comment]
Thanks for opening the issue and the PR. That PR looks good, if you're happy with it, merge it.

**Comment by PanagiotisPtr** [comment]
PR merged: https://github.com/PanagiotisPtr/cov-diff/pull/11

Closing issue
